In [1]:
import pandas as pd

In [2]:
stock=pd.read_csv('retdata.csv',sep='\t')
stock.head(n=3)

         Date  Hon Hai Precision  TSMC           Uni-President
0  2014-01-02             0.3745        -0.9479         0.5587
1  2014-01-03            -1.2438        -1.9139        -0.9259
2  2014-01-06            -0.5038         0.0000         0.0000

In [3]:
stock.index = pd.to_datetime(stock.Date)
UniPresident = stock.iloc[:,3]
UniPresident.head(n=3)

Date
2014-01-02    0.5587
2014-01-03   -0.9259
2014-01-06    0.0000
Name: Uni-President, dtype: float64

In [4]:
#讀入三因子資料
factors=pd.read_csv('factors.csv')
factors.head(n=3)

,Security Name,CoName,YY/MM/DD,Market Risk Premium,Size Factor (3 Factor),Book to Market Factor,Risk-free Interest Rate
0,Z8888,TSEC+GreTai Non-Banking index,2014/01/02,0.0145,0.7197,0.3039,1.355
1,Z8888,TSEC+GreTai Non-Banking index,2014/01/03,-0.5858,0.6868,1.0533,1.355
2,Z8888,TSEC+GreTai Non-Banking index,2014/01/06,-0.4534,0.5783,0.4498,1.355

In [5]:
factors.index =pd.to_datetime(factors['YY/MM/DD']) 
factors.columns

Index(['Security Name', 'CoName', 'YY/MM/DD', 'Market Risk Premium',
       'Size Factor (3 Factor)', 'Book to Market Factor',
       'Risk-free Interest Rate'],
      dtype='object')

In [6]:
#將年無風險利率轉化成日無風險利率
factors['Risk-free Interest Rate']=(factors['Risk-free Interest Rate']**(1/360)-1)*100
factors.head(n=10)

,Security Name,CoName,YY/MM/DD,Market Risk Premium,Size Factor (3 Factor),Book to Market Factor,Risk-free Interest Rate
YY/MM/DD,,,,,,,
2014-01-02,Z8888,TSEC+GreTai Non-Banking index,2014/01/02,0.0145,0.7197,0.3039,0.084425
2014-01-03,Z8888,TSEC+GreTai Non-Banking index,2014/01/03,-0.5858,0.6868,1.0533,0.084425
2014-01-06,Z8888,TSEC+GreTai Non-Banking index,2014/01/06,-0.4534,0.5783,0.4498,0.084425
2014-01-07,Z8888,TSEC+GreTai Non-Banking index,2014/01/07,0.1950,0.4554,0.7056,0.084425
2014-01-08,Z8888,TSEC+GreTai Non-Banking index,2014/01/08,0.6204,-0.0295,0.2259,0.084425
2014-01-09,Z8888,TSEC+GreTai Non-Banking index,2014/01/09,-0.5598,-0.1396,0.2177,0.084425
2014-01-10,Z8888,TSEC+GreTai Non-Banking index,2014/01/10,0.1987,0.1814,0.3059,0.084425
2014-01-13,Z8888,TSEC+GreTai Non-Banking index,2014/01/13,0.3855,-0.0812,-0.7102,0.084425
2014-01-14,Z8888,TSEC+GreTai Non-Banking index,2014/01/14,-0.1586,0.0444,-0.0732,0.084425
2014-01-15,Z8888,TSEC+GreTai Non-Banking index,2014/01/15,0.7094,-0.0390,0.0151,0.084425

In [7]:
data=pd.concat([UniPresident,factors.iloc[:,1:]],axis=1).dropna()
data.tail(n=3)

,Uni-President,CoName,YY/MM/DD,Market Risk Premium,Size Factor (3 Factor),Book to Market Factor,Risk-free Interest Rate
2014-12-29,1.1134,TSEC+GreTai Non-Banking index,2014/12/29,0.7341,-0.2407,-0.4195,0.084425
2014-12-30,0.1001,TSEC+GreTai Non-Banking index,2014/12/30,-0.1990,0.1720,-0.2125,0.084425
2014-12-31,0.4000,TSEC+GreTai Non-Banking index,2014/12/31,0.4774,0.0670,-0.2604,0.084425

In [8]:
data['Uni-President'] = data['Uni-President'] - data['Risk-free Interest Rate']
data['Uni-President']

2014-01-02    0.474275
2014-01-03   -1.010325
2014-01-06   -0.084425
2014-01-07   -0.271325
2014-01-08   -0.458925
                ...
2014-12-26   -0.084425
2014-12-27   -0.084425
2014-12-29    1.028975
2014-12-30    0.015675
2014-12-31    0.315575
Name: Uni-President, Length: 248, dtype: float64

In [9]:
import statsmodels.api as sm
#parif=data.iloc[:,3:6]
regThrFac=sm.OLS(data['Uni-President'],sm.add_constant(data.iloc[:,3:6]))
result=regThrFac.fit()
result.summary()

C:\Users\s0954\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:2389: FutureWarning: Method .ptp is deprecated and will be removed in a future version. Use numpy.ptp instead.
  return ptp(axis=axis, out=out, **kwargs)

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:          Uni-President   R-squared:                       0.293
Model:                            OLS   Adj. R-squared:                  0.284
Method:                 Least Squares   F-statistic:                     33.68
Date:                Sun, 02 May 2021   Prob (F-statistic):           2.99e-18
Time:                        16:26:43   Log-Likelihood:                -393.91
No. Observations:                 248   AIC:                             795.8
Df Residuals:                     244   BIC:                             809.9
Df Model:                           3
Covariance Type:            nonrobust
==========================================================================================
                             coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------
const                     -0.1174      0.076     -1.543      0.124      -0.267       0.032
Market Risk Premium        1.0794      0.112      9.622      0.000       0.858       1.300
Size Factor (3 Factor)    -0.0568      0.159     -0.357      0.722      -0.371       0.257
Book to Market Factor     -0.0142      0.208     -0.068      0.946      -0.424       0.396
==============================================================================
Omnibus:                       46.399   Durbin-Watson:                   2.153
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              344.846
Skew:                           0.435   Prob(JB):                     1.31e-75
Kurtosis:                       8.711   Cond. No.                         2.88
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [10]:
#利用params提取模型係數
result.params

const                    -0.117379
Market Risk Premium       1.079372
Size Factor (3 Factor)   -0.056831
Book to Market Factor    -0.014195
dtype: float64